# Generated by Django 3.0 on 2023-04-29 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20230429_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sosi',
        ),
        migrations.AddField(
            model_name='event',
            name='sosiName',
            field=models.TextField(blank=True, null=True, verbose_name='sosiName'),
        ),
        migrations.AddField(
            model_name='event',
            name='timeOfSosi',
            field=models.DateField(auto_now=True, verbose_name='timeOfSosi'),
        ),
    ]
