# Generated by Django 3.0 on 2023-05-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_myclubuser_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='sosiName',
        ),
        migrations.RemoveField(
            model_name='event',
            name='timeOfSosi',
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.TextField(blank=True, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.DateField(auto_now=True, verbose_name='time'),
        ),
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, to='events.MyClubUser'),
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.Venue'),
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='secondName',
            field=models.TextField(blank=True, verbose_name='secondName'),
        ),
    ]
