# Generated by Django 3.0 on 2023-05-20 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20230520_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='time'),
        ),
    ]
