# Generated by Django 3.0 on 2023-05-20 10:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_auto_20230520_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='time'),
        ),
    ]
