# Generated by Django 3.0 on 2023-05-25 13:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20230520_1751'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='event',
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='venue',
            managers=[
                ('venues', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='myclubuser',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
